test github actions

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -7,22 +7,23 @@ on:
 
 jobs:
   lint:
+    name: Linting check
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      
+      - uses: actions/checkout@v2
+
       - name: Install dependencies
         run: npm install
-        
+
       - name: Run linting
         run: npm run lint
 
       - name: Check if no errors
-      run: |
-        if [ $? -eq 0 ]; then
-          echo "Linting succeeded"
-        else
-          echo "Linting failed"
-          exit 1
-        fi
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Linting succeeded"
+          else
+            echo "Linting failed"
+            exit 1
+          fi
